server:
  port: 8090
spring:
  # Swagger 2 显示地址 http://localhost:8088/swagger-ui.html
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  # 热部署生效
  devtools:
    restart:
      enabled: true