spring:
  rabbitmq:
    host: 127.0.0.1
    username: admin
    password: 123456
    port: 5672
    virtual-host: /
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 100
