# 开发环境
server:
  port: 8090
spring:
  # Swagger显示地址 http://localhost:8090/swagger-ui/index.html
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  # 热部署生效
  devtools:
    restart:
      enabled: true